// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmZ74hHlKgyjIExASHzCFENH0EDjAr5RI',
    appId: '1:705363425878:web:5508c427927167dbe219f7',
    messagingSenderId: '705363425878',
    projectId: 'stoicquote-24d95',
    authDomain: 'stoicquote-24d95.firebaseapp.com',
    storageBucket: 'stoicquote-24d95.firebasestorage.app',
    measurementId: 'G-9S8BVJ71YN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsbOyFayZbehN8-vFoq4S_YbInuRFgdLo',
    appId: '1:705363425878:android:4d29a6ae21553c82e219f7',
    messagingSenderId: '705363425878',
    projectId: 'stoicquote-24d95',
    storageBucket: 'stoicquote-24d95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlZ-0reLE3CDzsSIboFf86zjqwNaam9zg',
    appId: '1:705363425878:ios:1afbe5a30500fcd2e219f7',
    messagingSenderId: '705363425878',
    projectId: 'stoicquote-24d95',
    storageBucket: 'stoicquote-24d95.firebasestorage.app',
    iosBundleId: 'com.example.stoicQuotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlZ-0reLE3CDzsSIboFf86zjqwNaam9zg',
    appId: '1:705363425878:ios:1afbe5a30500fcd2e219f7',
    messagingSenderId: '705363425878',
    projectId: 'stoicquote-24d95',
    storageBucket: 'stoicquote-24d95.firebasestorage.app',
    iosBundleId: 'com.example.stoicQuotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmZ74hHlKgyjIExASHzCFENH0EDjAr5RI',
    appId: '1:705363425878:web:1892c70118e23bc9e219f7',
    messagingSenderId: '705363425878',
    projectId: 'stoicquote-24d95',
    authDomain: 'stoicquote-24d95.firebaseapp.com',
    storageBucket: 'stoicquote-24d95.firebasestorage.app',
    measurementId: 'G-SST3JHSTC5',
  );
}
